### PR TITLE
Aesthetic work on cockpit panel

### PR DESCRIPTION
**Pull request by RenanMsV**

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
@RenanMsV @FGDATA do you have permission to use that texture from pinterest? 
it looks great but I'm worried about licensing

**Comment by RenanMsV** [comment]
After more search, I did found this image in a Wikipedia page about this helicopter. https://it.wikipedia.org/wiki/AgustaWestland_AW139#/media/File:Italian_Air_Force_AW139.jpg  
So this image come from http://jetphotos.net/viewphoto.php?id=7475975&nseq=11 wich is offline.
And appears that this image have a GFDL license. http://www.gnu.org/licenses/old-licenses/fdl-1.2.html

"The purpose of this License is to make a manual, textbook, or other functional and useful document "free" in the sense of freedom: to assure everyone the effective freedom to copy and redistribute it, with or without modifying it, either commercially or noncommercially. Secondarily, this License preserves for the author and publisher a way to get credit for their work, while not being considered responsible for modifications made by others.
This License is a kind of "copyleft", which means that derivative works of the document must themselves be free in the same sense. It complements the GNU General Public License, which is a copyleft license designed for free software.
We have designed this License in order to use it for manuals for free software, because free software needs free documentation..."

Flight simulators are somewhat academic material. So I'll let you decide.

**Comment by IAHM-COL** [comment]
I think that having the image in the helicopter source proves no immediate
benefit.
A link to the image could be placed in a readme file for those interest,
but I don't understand the need to bring the image itself in.
Maybe I am missing something?

Also, adding a 7z backup file seems strange.

**Comment by legoboyvdlp** [comment]
@IAHM-COL it looks as if he used it as the texture? 
not as the source

**Comment by FGDATA** [comment]
Oh Ok!
Sounds good then. @RenanMsV , can you verify this image is used for texturization? Also, would you be able to commit again, but without the backup 7Z file?

Best
@IAHM-COL

**Comment by RenanMsV** [comment]
Yes it is for texturization. I'll commit again.

**Comment by FGDATA** [comment]
Thanks :dart:

**Pull request merged**
